//The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number
// would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
//1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
//Let us list the factors of the first seven triangle numbers:
//
// 1: 1
// 3: 1,3
// 6: 1,2,3,6
//10: 1,2,5,10
//15: 1,3,5,15
//21: 1,3,7,21
//28: 1,2,4,7,14,28
//We can see that 28 is the first triangle number to have over five divisors.
//What is the value of the first triangle number to have over five hundred divisors?

public class PS12 {
    public static void calculateDivisor(){
        int predict = 1;
        int triangle = 0;
        int count = 0;
        boolean check = true;
        while(check){
            triangle = triangle(predict);
            count = countDivisor(triangle);
            if(count > 500){
                check = false;
            }
            predict++;
        }
        System.out.println("Triangle number is " + triangle);
    }
    public static int triangle(int n){
        int triangle = 0;
        for(int i =0;i<=n;i++){
            triangle += i;
        }
        return triangle;
    }
    public static int countDivisor(int n){
        int count = 0;
        for(int i=1;i<=n;i++){
            if(n % i == 0){
                count++;
            }
        }
        return count;
    }
}
